export class BadWords {

    public badwords: Array<any> = [
        'anus',
        'ânus',
        'arrombado',
        'babaca',
        'babaovo',
        'baba-ovo',
        'bagos',
        'baitola',
        'bebum',
        'bicha',
        'bichinha',
        'bixa',
        'bixinha',
        'boceta',
        'boiola',
        'boquete',
        'boqueteira',
        'boqueteiro',
        'bosseta',
        'bosta',
        'brioco',
        'buceta',
        'bunda',
        'burra',
        'burro',
        'busseta',
        'caceta',
        'cacete',
        'cachorra',
        'cachorro',
        'cadela',
        'caga',
        'cagado',
        'cagao',
        'cagona',
        'canalha',
        'capeta',
        'caralho',
        'casa do caralho',
        'casseta',
        'cassete',
        'checheca',
        'chereca',
        'chifruda',
        'chifrudo',
        'chochota',
        'chota',
        'chupa meu cu',
        'chupa meu pau',
        'chupa',
        'clitoris',
        'cocaina',
        'coco',
        'comer seu cu',
        'comer voce',
        'comer você',
        'corna',
        'corno',
        'cornuda',
        'cornudo',
        'corrupta',
        'corrupto',
        'crack',
        'cretina',
        'cretino',
        'cruz credo',
        'cruz-credo',
        'cu',
        'cuzao',
        'cuzuda',
        'debil',
        'débil',
        'debiloide',
        'debilóide',
        'defunto',
        'demente',
        'dementes',
        'demonio',
        'demônio',
        'desgraca',
        'desgraçada',
        'desgraçado',
        'difunto',
        'doida',
        'doido',
        'droga',
        'drogas',
        'egua',
        'égua',
        'escrota',
        'escroto',
        'esporro',
        'estrupar',
        'estupida',
        'estúpida',
        'estupidez',
        'estupido',
        'estúpido',
        'estuprar',
        'fedida',
        'fedido',
        'fedor',
        'fedorenta',
        'fedorento',
        'feia',
        'feio',
        'feiosa',
        'feioso',
        'feioza',
        'feiozo',
        'foda se',
        'foda',
        'foda-se',
        'fodido',
        'fornica',
        'fudecao',
        'fudendo',
        'fudido',
        'furnica',
        'gay',
        'gayzinho',
        'gonorrea',
        'gonorreia',
        'gozada',
        'gozar',
        'grelinho',
        'grelo',
        'homosexual',
        'homo-sexual',
        'homossexual',
        'idiota',
        'idiotice',
        'imbecil',
        'inferno',
        'iscrota',
        'ladra',
        'ladrao',
        'ladrão',
        'ladroeira',
        'ladrona',
        'lalau',
        'leprosa',
        'leproso',
        'lesbica',
        'lésbica',
        'macaca',
        'macaco',
        'maconha',
        'masturba',
        'masturbar',
        'meleca',
        'merda',
        'mija',
        'mijada',
        'mijado',
        'mijo',
        'mocrea',
        'mocreia',
        'moleca',
        'moleque',
        'nojenta',
        'nojento',
        'otaria',
        'otária',
        'paspalha',
        'paspalho',
        'pau no cu',
        'pau no seu cu',
        'pau no',
        'pau',
        'peido',
        'peitos',
        'penis',
        'pênis',
        'pentelha',
        'pentelho',
        'perereca',
        'peru',
        'peste',
        'pinto',
        'piranha',
        'piroca',
        'piroco',
        'piru',
        'porno',
        'porra',
        'pozinho',
        'pqp',
        'prost-bulo',
        'prostibulo',
        'prostíbulo',
        'prostituta',
        'prostituto',
        'punheta',
        'punhetao',
        'punhetão',
        'pura que pariu',
        'puta que pariu',
        'puta',
        'puto',
        'puxa saco',
        'puxasaco',
        'puxa-saco',
        'rabao',
        'rabão',
        'rabo',
        'rabuda',
        'rabudo',
        'rabudona',
        'reatardada',
        'retardado',
        'ridicula',
        'ridícula',
        'rola',
        'rosca',
        'sacana',
        'safada',
        'safado',
        'sapatao',
        'sapatão',
        'sastanas',
        'satanas',
        'sexo',
        'tarada',
        'tarado',
        'tesao',
        'tesão',
        'testuda',
        'testudo',
        'tezao',
        'tezuda',
        'tezudo',
        'troucha',
        'trouxa',
        'troxa',
        'vaca',
        'vadia',
        'vagabunda',
        'vagabundo',
        'vagina',
        'vai dar a buceta',
        'vai dar o cu',
        'vai pra merda',
        'vai tomar no cu',
        'veada',
        'veadao',
        'veadinho',
        'veado',
        'viada',
        'viadao',
        'viadão',
        'viadinho',
        'viado',
        'vou matar sua familia',
        'vou te comer',
        'vou te estrupar',
        'vou te estuprar',
        'vou te matar',
        'vou te pegar',
        'vsf',
        'vtnc',
        'xana',
        'xaninha',
        'xereca',
        'xexeca',
        'xochota',
        'xota',
        'xoxota',
        'xvideos',
        'ze buceta',
        'ze droguina',
        'ze droguinha',
        'ze-buceta',
        'ze-buceta',
        'ze-droguina',
        'ze-droguinha',
    ]
    constructor() { }

}